@startuml
title Delete Criminal Record

actor Client
participant "Website Criminal Records page" as CriminalRecordsPage
participant DeleteCriminalRecordsActivity
database CriminalRecord

Client -> CriminalRecordsPage : DELETE /criminalrecords/{ssn}
CriminalRecordsPage -> DeleteCriminalRecordsActivity : Send DELETE request
DeleteCriminalRecordsActivity -> CriminalRecord : delete CriminalRecord by SSN

alt if SSN does not exist
CriminalRecord --> DeleteCriminalRecordsActivity : throw NoCriminalRecordException
DeleteCriminalRecordsActivity --> CriminalRecordsPage : return message "No Criminal Records"
end

CriminalRecord --> CriminalRecordsPage : messate "Record was deleted"

@enduml
