@startuml
title Get Criminal Record

actor Client
participant "Website Criminal Records page" as CriminalRecordsPage
participant GetCriminalRecordsActivity
database CriminalRecord

Client -> CriminalRecordsPage : GET /criminalrecords/{ssn}
CriminalRecordsPage -> GetCriminalRecordsActivity : Send GET request
GetCriminalRecordsActivity -> CriminalRecord : load CriminalRecord by SSN

alt if SSN does not exist
CriminalRecord --> GetCriminalRecordsActivity : throw NoCriminalRecordException
GetCriminalRecordsActivity --> CriminalRecordsPage : return message "No Criminal Records"
end

CriminalRecord --> CriminalRecordsPage : CriminalRecord

@enduml
