@startuml
title Get Crimes from Criminal Record

actor Client
participant "Website Crime page" as CrimePage
participant GetCrimesFromCriminalRecordActivity
database CriminalRecord

Client -> CrimePage : GET /criminalrecords/{ssn}/crimes
CrimePage -> GetCrimesFromCriminalRecordActivity : Send GET request to retrieve a list of crimes
GetCrimesFromCriminalRecordActivity -> CriminalRecord : load List<Crimes>

alt if SSN does not exist
CriminalRecord --> GetCrimesFromCriminalRecordActivity : throw NoCriminalRecordException
GetCrimesFromCriminalRecordActivity --> CrimePage : return message "No Criminal Records"
end

CriminalRecord --> CrimePage : List<Crimes>

@enduml
