Resources:
  CriminalRecordsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: CriminalRecords
      AttributeDefinitions:
        - AttributeName: "ssn"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ssn"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"